// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/search/[search].ts";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/heroHeader.tsx";
import * as $$1 from "./islands/searchBar.tsx";

const manifest = {
  routes: {
    "./routes/api/search/[search].ts": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/heroHeader.tsx": $$0,
    "./islands/searchBar.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
